import argparse
import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from moon_claude.core.bus.commands import PingCommand, PongResult
from moon_claude.core.bus.events import CoreStartedEvent

# 定义默认输出路径
_OUTPUT_PATH = Path(__file__).parent.parent / "WIRE_PROTOCOL.md"


# 从 pydantic 模型生成一个带字段表、JSON Schema 和可选示例的 Markdown 小节
def _model_section(
    name: str,
    model: type[BaseModel],
    example: dict[str, Any] | None = None,
) -> str:
    schema = model.model_json_schema()
    props = schema.get("properties", {})
    required: set[str] = set(schema.get("required", []))

    table = ""
    if props:
        table = "\n| Field | Type | Required |\n|---|---|---|\n"
        for field_name, field_info in props.items():
            ftype = field_info.get("type", "object")
            if "anyOf" in field_info:
                ftype = " | ".join(t.get("type", "?") for t in field_info["anyOf"])
            req = "yes" if field_name in required else "no"
            table += f"| `{field_name}` | `{ftype}` | {req} |\n"

    schema_block = f"\n```json\n{json.dumps(schema, indent=2)}\n```\n"

    example_block = ""
    if example:
        example_block = f"\n**Example:**\n\n```json\n{json.dumps(example, indent=2)}\n```\n"

    return f"### {name}\n{table}{schema_block}{example_block}"


# 生成完整的 WIRE_PROTOCOL.md 文档字符串
def generate() -> str:
    ts = "2026-06-22T10:00:00.001Z"

    ping_req_example = {
        "jsonrpc": "2.0",
        "id": "u-1",
        "method": "core.ping",
        "params": {"client": "cli/0.0.1"},
    }
    pong_resp_example = {
        "jsonrpc": "2.0",
        "id": "u-1",
        "result": {
            "server_version": "0.0.1",
            "uptime_ms": 12,
            "received_at": ts,
        },
    }

    sections = [
        "# Wire Protocol\n\n",
        "> Generated by `scripts/gen_protocol_doc.py`. **Do not edit manually.**\n\n",
        "## Transport\n\n",
        "- TCP loopback `127.0.0.1:7437` (override via `MOON_HOST` / `MOON_PORT`)\n",
        "- Each message is one `\\n`-terminated JSON line (NDJSON)\n",
        (
            "- Commands use JSON-RPC 2.0 (client → server); "
            "Events use `kind=event` envelope (server → client)\n\n"
        ),
        "## Commands\n\n",
        (
            "All commands are sent as JSON-RPC 2.0 requests. "
            "The `type` field inside `params` is used for routing.\n\n"
        ),
        _model_section("PingCommand", PingCommand, ping_req_example),
        "\n",
        _model_section("PongResult", PongResult, pong_resp_example),
        "\n",
        "\n## Events\n\n",
        _model_section("CoreStartedEvent", CoreStartedEvent),
        "\n",
        "\n## Error Codes\n\n",
        "| Code | Name | Meaning |\n",
        "|------|------|---------|\n",
        "| -32700 | Parse Error | Invalid JSON received |\n",
        "| -32600 | Invalid Request | Missing required JSON-RPC fields |\n",
        "| -32601 | Method Not Found | Unknown method |\n",
        "| -32602 | Invalid Params | Parameter validation failed |\n",
        "| -32603 | Internal Error | Handler raised an unhandled exception |\n",
    ]

    return "".join(sections)  # sections 保存很多段 Markdown 字符串，join() 把它们连接成一篇完整文档


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate WIRE_PROTOCOL.md")
    parser.add_argument(
        "--check",
        action="store_true",  # 出现 --check 时值为 True
        help="Verify file matches generated output",
    )
    parser.add_argument("--output", default=str(_OUTPUT_PATH))
    args = parser.parse_args()

    content = generate()
    output_path = Path(args.output)

    if args.check:
        if not output_path.exists():
            print(
                f"ERROR: {output_path} not found — run the generator first",
                file=sys.stderr,
            )
            sys.exit(1)

        if output_path.read_text(encoding="utf-8") != content:
            print(
                f"ERROR: {output_path} is out of sync — run the generator",
                file=sys.stderr,
            )
            sys.exit(1)

        print(f"OK: {output_path} is up to date.")
        return

    output_path.write_text(content, encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
